export const CART_ADD_ITEM_REQUEST = 'CART_ADD_ITEM_REQUEST'
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS'
export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL'
export const CART_ADD_ITEM_RESET = 'CART_ADD_ITEM_RESET'

export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST'
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS'
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL'

export const CART_LIST_MY_REQUEST = 'CART_LIST_MY_REQUEST'
export const CART_LIST_MY_SUCCESS = 'CART_LIST_MY_SUCCESS'
export const CART_LIST_MY_FAIL = 'CART_LIST_MY_FAIL'
export const CART_LIST_MY_RESET = 'CART_LIST_MY_RESET'

export const CART_CLEAN_REQUEST = 'CART_CLEAN_REQUEST'
export const CART_CLEAN_SUCCESS = 'CART_CLEAN_SUCCESS'
export const CART_CLEAN_FAIL = 'CART_CLEAN_FAIL'

export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_CLEAN_ITEM = 'CART_CLEAN_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
