export const FAVOURITE_ADD_REQUEST = 'FAVOURITE_ADD_REQUEST'
export const FAVOURITE_ADD_SUCCESS = 'FAVOURITE_ADD_SUCCESS'
export const FAVOURITE_ADD_FAIL = 'FAVOURITE_ADD_FAIL'
export const FAVOURITE_ADD_RESET = 'FAVOURITE_ADD_RESET'

export const FAVOURITE_REMOVE_REQUEST = 'FAVOURITE_REMOVE_REQUEST'
export const FAVOURITE_REMOVE_SUCCESS = 'FAVOURITE_REMOVE_SUCCESS'
export const FAVOURITE_REMOVE_FAIL = 'FAVOURITE_REMOVE_FAIL'

export const FAVOURITE_REQUEST = 'FAVOURITE_REQUEST'
export const FAVOURITE_SUCCESS = 'FAVOURITE_SUCCESS'
export const FAVOURITE_FAIL = 'FAVOURITE_FAIL'
