export const GOODS_LIST_REQUEST = "GOODS_LIST_REQUEST";
export const GOODS_LIST_SUCCESS = "GOODS_LIST_SUCCESS";
export const GOODS_LIST_FAIL = "GOODS_LIST_FAIL";

export const GOODS_CREATE_REQUEST = "GOODS_CREATE_REQUEST";
export const GOODS_CREATE_SUCCESS = "GOODS_CREATE_SUCCESS";
export const GOODS_CREATE_FAIL = "GOODS_CREATE_FAIL";
export const GOODS_CREATE_RESET = 'GOODS_CREATE_RESET'

export const GOODS_UPDATE_REQUEST = "GOODS_UPDATE_REQUEST";
export const GOODS_UPDATE_SUCCESS = "GOODS_UPDATE_SUCCESS";
export const GOODS_UPDATE_FAIL = "GOODS_UPDATE_FAIL";
export const GOODS_UPDATE_RESET = 'GOODS_UPDATE_RESET'


export const GOODS_DELETE_REQUEST = "GOODS_DELETE_REQUEST";
export const GOODS_DELETE_SUCCESS = "GOODS_DELETE_SUCCESS";
export const GOODS_DELETE_FAIL = "GOODS_DELETE_FAIL";

export const GOODS_DETAILS_REQUEST = "GOODS_DELETE_REQUEST";
export const GOODS_DETAILS_SUCCESS = "GOODS_DELETE_SUCCESS";
export const GOODS_DETAILS_FAIL = "GOODS_DELETE_FAIL";

export const GOODS_TOP_REQUEST = 'GOODS_TOP_REQUEST'
export const GOODS_TOP_SUCCESS = 'GOODS_TOP_SUCCES'
export const GOODS_TOP_FAIL = 'GOODS_TOP_FAIL'

export const GOODS_CREATE_REVIEW_REQUEST = 'GOODS_CREATE_REVIEW_REQUEST'
export const GOODS_CREATE_REVIEW_SUCCESS = 'GOODS_CREATE_REVIEW_SUCCES'
export const GOODS_CREATE_REVIEW_FAIL = 'GOODS_CREATE_REVIEW_FAIL'
export const GOODS_CREATE_REVIEW_RESET = 'GOODS_CREATE_REVIEW_RESET'