export const HISTORY_ADD_REQUEST = 'HISTORY_ADD_REQUEST'
export const HISTORY_ADD_SUCCESS = 'HISTORY_ADD_SUCCESS'
export const HISTORY_ADD_FAIL = 'HISTORY_ADD_FAIL'
export const HISTORY_ADD_RESET = 'HISTORY_ADD_RESET'

export const HISTORY_REQUEST = 'HISTORY_REQUEST'
export const HISTORY_SUCCESS = 'HISTORY_SUCCESS'
export const HISTORY_FAIL = 'HISTORY_FAIL'