export const WANTED_ADD_REQUEST = 'WANTED_ADD_REQUEST'
export const WANTED_ADD_SUCCESS = 'WANTED_ADD_SUCCESS'
export const WANTED_ADD_FAIL = 'WANTED_ADD_FAIL'
export const WANTED_ADD_RESET = 'WANTED_ADD_RESET'

export const WANTED_REMOVE_REQUEST = 'WANTED_REMOVE_REQUEST'
export const WANTED_REMOVE_SUCCESS = 'WANTED_REMOVE_SUCCESS'
export const WANTED_REMOVE_FAIL = 'WANTED_REMOVE_FAIL'

export const WANTED_REQUEST = 'WANTED_REQUEST'
export const WANTED_SUCCESS = 'WANTED_SUCCESS'
export const WANTED_FAIL = 'WANTED_FAIL'